### ISSUE TITLE
helmfile environment

### ISSUE THREAD

**Issue by felix-sift** [lucj/argocd-helmfile-plugin#10]
we deploy helmfile with different environments. is there a way to pass then environment into the argocd application somehow?

**Comment by lucj** [comment]
Hello,
You can use env within the plugin property.
ENV_NAME is the property you can set in a cluster definition in argocd.

```
plugin: 
          env:
            - name: ENV_NAME
              value: '{{metadata.labels.ENV_NAME}}'
```
Doing so, it will select this specific helmfile environment.
